### ISSUE TITLE
脚本失效了

### ISSUE THREAD

**Issue by bamboo1214** [yuhaofe/Video-Quality-Fixer-for-Twitter#3]
现在的0.1.4版打开Twitter视频画质默认不是最高，也没有HQ标志显示。

**Comment by yuhaofe** [comment]
已修复，由于修改了作者名称，可能无法自动更新，请前往[Greasyfork页面](https://greasyfork.org/zh-CN/scripts/399827-video-quality-fixer-for-twitter)重新安装
