### ISSUE TITLE
Request: add download button for video

### ISSUE THREAD

**Issue by DB9-max** [yuhaofe/Video-Quality-Fixer-for-Twitter#6]
Request: add download button for video

**Comment by yuhaofe** [comment]
There are many twitter video download scripts and services out there, I want to keep this script as simple as possible. Thanks for your understanding.

**Comment by DB9-max** [comment]
> There are many twitter video download scripts and services out there, I want to keep this script as simple as possible. Thanks for your understanding.

The script still functions? Perhaps add highest quality images too?

**Comment by DB9-max** [comment]
"updated 2 days ago" 👍
